import { createContext, useContext, useState, useEffect, useCallback } from 'react'
import { useSettings } from './SettingsContext'

const LangContext = createContext({})
export const useLang = () => useContext(LangContext)

export const translations = {
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    employees: 'إدارة الموظفين',
    attendance: 'سجل الحضور والغياب',
    clients: 'قاعدة العملاء',
    deals: 'إدارة الصفقات',
    products: 'المخزن والأصناف',
    suppliers: 'قائمة الموردين',
    transactions: 'الحسابات والخزنة',
    invoices: 'الفواتير والمبيعات',
    payroll: 'شؤون الرواتب',
    settings: 'إعدادات النظام',

    // Auth
    signOut: 'تسجيل الخروج',
    signIn: 'تسجيل الدخول',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    loading: 'جاري التحميل...',
    connected: 'متصل',
    register: 'إنشاء حساب',
    fullName: 'الاسم بالكامل',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    noAccount: 'ليس لديك حساب؟ سجل الآن',
    registrationSuccess: 'تم إنشاء الحساب بنجاح! يمكنك الدخول الآن.',
    newRegistration: 'تسجيل موظف جديد',
    newRegistrationBody: 'قام {name} بإنشاء حساب جديد كـ موظف.',
    notifications: 'التنبيهات',
    markAllRead: 'تحديد الكل كمقروء',
    noNotifications: 'لا توجد تنبيهات جديدة',
    lowStockAlert: 'تنبيه مخزون منخفض',
    dealClosingAlert: 'تنبيه إغلاق صفقة',
    overdueInvoiceAlert: 'تنبيه فاتورة متأخرة',
    payrollAlert: 'تنبيه صرف رواتب',

    // Settings Page
    settingsTitle: 'إعدادات النظام',
    settingsSubtitle: 'إدارة بيانات شركتك وتفضيلات النظام',
    companyInfo: 'بيانات الشركة',
    companyName: 'اسم الشركة',
    companyAddress: 'العنوان',
    companyPhone: 'رقم الهاتف',
    companyEmail: 'البريد الإلكتروني',
    taxNumber: 'الرقم الضريبي',
    currency: 'العملة',
    currencySymbol: 'رمز العملة',
    companyLogo: 'شعار الشركة',
    uploadLogo: 'رفع شعار جديد',
    logoHint: 'PNG أو JPG بحجم أقصى 2MB',
    logoPreview: 'معاينة الشعار',
    noLogo: 'لا يوجد شعار',

    // Invoice Settings
    invoiceSettings: 'إعدادات الفاتورة',
    invoiceNotes: 'ملاحظات الفاتورة',
    invoiceFooter: 'تذييل الفاتورة',
    invoiceColor: 'لون الفاتورة',
    invoicePrefix: 'بادئة رقم الفاتورة',
    invoiceTaxRate: 'نسبة الضريبة %',
    invoiceShowLogo: 'إظهار الشعار في الفاتورة',
    invoiceShowTax: 'إظهار الضريبة',
    invoiceNotesPlaceholder: 'شكراً لتعاملكم معنا...',
    invoiceFooterPlaceholder: 'البنك: ××× | رقم الحساب: ×××',

    // Payroll Settings
    payrollSettings: 'إعدادات الرواتب',
    payrollDay: 'يوم صرف الرواتب',
    workingHours: 'ساعات العمل اليومية',
    latePenaltyPerHour: 'خصم التأخير (لكل ساعة)',

    // Notification Settings
    notificationSettings: 'إعدادات التنبيهات',
    notifyLowStock: 'تنبيه المخزون المنخفض',
    notifyLowStockDays: 'الحد الأدنى للمخزون',
    notifyDealsClosing: 'تنبيه الصفقات القريبة الإغلاق',
    notifyDealsClosingDays: 'قبل كم يوم',
    notifyOverdueInvoices: 'تنبيه الفواتير المتأخرة',
    notifyBirthdays: 'تنبيه أعياد الميلاد',
    notifyPayroll: 'تنبيه صرف الرواتب',

    // User Management
    userManagement: 'إدارة المستخدمين',
    userManagementSubtitle: 'تحكم في صلاحيات وأدوار المستخدمين',
    changeRole: 'تغيير الدور',
    roleUpdated: 'تم تحديث الدور',

    // Language Settings
    languageSettings: 'إعدادات اللغة',
    languageLabel: 'لغة الواجهة',
    arabic: 'العربية',
    english: 'English',
    direction: 'اتجاه الكتابة',
    rtl: 'يمين إلى يسار (RTL)',
    ltr: 'يسار إلى يمين (LTR)',

    // Actions
    save: 'حفظ التغييرات',
    saving: 'جاري الحفظ...',
    saved: 'تم الحفظ بنجاح',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    add: 'إضافة',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير Excel',
    exportPDF: 'تصدير PDF',
    print: 'طباعة',
    preview: 'معاينة',
    view: 'عرض',

    // Status
    active: 'نشط',
    inactive: 'غير نشط',
    pending: 'معلق',
    draft: 'مسودة',
    sent: 'مرسلة',
    paid: 'مدفوعة',
    cancelled: 'ملغاة',
    overdue: 'متأخرة',
    present: 'حضور',
    absent: 'غياب',
    leave: 'إجازة',
    holiday: 'عطلة',
    vegetables: 'خضروات',
    fruits: 'فاكهة',
    legumes: 'بقوليات',
    kg: 'كيلو جرام',
    ton: 'طن متري',
    carton: 'كرتونة',
    sack: 'شوال / جوال',
    piece: 'قطعة / وحدة',
    contact: 'تواصل',
    negotiation: 'تفاوض',
    contracted: 'تم التعاقد',
    facebook: 'فيسبوك',
    instagram: 'انستجرام',
    google: 'جوجل',
    referral: 'ترشيح',
    direct: 'مباشر',
    other: 'أخرى / متنوع',
    retail: 'تجزئة',
    wholesale: 'جملة',

    // Roles
    admin: 'مدير النظام (Admin)',
    employee: 'موظف (Employee)',
    manager: 'مدير عام (Manager)',
    accountant: 'محاسب مالي (Accountant)',
    sales: 'مسؤول مبيعات (Sales)',
    hr: 'موارد بشرية (HR)',
    labor: 'فني / عامل (Labor)',
    station: 'المحطة',
    allStations: 'كل المحطات',
    allRoles: 'كل الوظائف',
    selectStation: 'اختر المحطة',

    // Errors
    errorSaving: 'حدث خطأ أثناء الحفظ',
    errorUploading: 'حدث خطأ أثناء رفع الملف',
    errorLoading: 'حدث خطأ أثناء التحميل',
    fileTooLarge: 'حجم الملف كبير جداً (الحد الأقصى 2MB)',
    invalidFileType: 'نوع الملف غير مدعوم',
    accessDenied: 'ليس لديك صلاحية للوصول لهذه الصفحة',

    // Dashboard
    welcomeBack: 'مرحباً بعودتك',
    totalEmployees: 'إجمالي الموظفين',
    totalClients: 'إجمالي العملاء',
    totalDeals: 'إجمالي الصفقات',
    totalRevenue: 'إجمالي الإيرادات',
    recentActivity: 'النشاط الأخير',
    quickActions: 'إجراءات سريعة',
    presentToday: 'حاضرين اليوم',
    activeDeals: 'صفقات نشطة',
    lowStockItems: 'منتجات ناقصة',
    monthRevenue: 'إيرادات الشهر',
    monthExpense: 'مصروفات الشهر',
    revenueExpenseChart: 'الإيرادات والمصروفات',
    last6Months: 'آخر 6 شهور',
    latestTransactions: 'آخر المعاملات المالية',
    noTransactions: 'لا توجد معاملات بعد',
    revenue: 'إيرادات',
    expense: 'مصروفات تشغيلية',
    salary: 'رواتب وأجور',
    advance: 'سلف موظفين',
    deduction: 'خصومات وجزاءات',
    waste: 'هالك / فواقد',
    purchase_payment: 'دفعات الموردين',
    client_payment: 'تحصيل من عملاء',
    maintenance: 'صيانة وإصلاحات',
    aiInsights: 'رؤى الذكاء الاصطناعي',
    stationComparison: 'مقارنة المحطات (الأداء المالي)',
    expenseBreakdown: 'توزيع المصاريف (هذا الشهر)',
    all: 'الكل',

    // Common
    name: 'الاسم',
    phone: 'الهاتف',
    address: 'العنوان',
    date: 'التاريخ',
    amount: 'المبلغ',
    total: 'الإجمالي',
    status: 'الحالة',
    actions: 'الإجراءات',
    notes: 'ملاحظات',
    user: 'مستخدم',
    role: 'الدور الوظيفي',
    noData: 'لا توجد بيانات',
    confirm: 'تأكيد',
    close: 'إغلاق',
    yes: 'نعم',
    no: 'لا',
    from: 'من',
    to: 'إلى',
    month: 'الشهر',
    year: 'السنة',
    subtotal: 'المجموع الفرعي',
    tax: 'الضريبة',
    discount: 'الخصم',
    net: 'الصافي',
    quantity: 'الكمية',
    unitPrice: 'سعر الوحدة',
    description: 'الوصف',
    item: 'بند',
    addItem: 'إضافة بند',
    removeItem: 'حذف البند',
    nameRequired: 'الاسم مطلوب',
    invalidAmount: 'أدخل مبلغ صحيح',
    transaction: 'معاملة',
    cash: 'كاش',
    transfer: 'تحويل بنكي',
    check: 'شيك',
    nameRequired: 'الاسم مطلوب',
    updateSuccess: 'تم التحديث بنجاح',
    addSuccess: 'تمت الإضافة بنجاح',
    deleteConfirm: 'هل أنت متأكد من الحذف؟',
    deleteSuccess: 'تم الحذف بنجاح',
    noActiveEmployees: 'لا يوجد موظفين نشطين',

    // Invoices
    newInvoice: 'فاتورة جديدة',
    invoiceNumber: 'رقم الفاتورة',
    invoiceDate: 'تاريخ الإصدار',
    dueDate: 'تاريخ الاستحقاق',
    client: 'العميل',
    deal: 'الصفقة',
    invoiceItems: 'بنود الفاتورة',
    invoiceTotal: 'إجمالي الفاتورة',
    markAsPaid: 'تحديد كمدفوعة',
    markAsSent: 'تحديد كمرسلة',
    confirmDelete: 'هل أنت متأكد من الحذف؟',
    generatePDF: 'إنشاء PDF',
    invoicePreview: 'معاينة الفاتورة',
    noInvoices: 'لا توجد فواتير بعد',

    // Payroll
    payrollTitle: 'كشف الرواتب',
    payrollSubtitle: 'حساب وصرف رواتب الموظفين',
    basicSalary: 'الراتب الأساسي',
    attendanceDays: 'أيام الحضور',
    absenceDays: 'أيام الغياب',
    overtimeHours: 'ساعات إضافي',
    overtimeAmount: 'قيمة الإضافي',
    bonuses: 'مكافآت',
    deductions: 'خصومات',
    advances: 'سلف الشهر',
    netSalary: 'الراتب الصافي',
    calculatePayroll: 'حساب الرواتب',
    payAll: 'صرف الكل',
    paySingle: 'صرف',
    payrollPaid: 'تم الصرف',
    payrollDraft: 'مسودة',
    noPayroll: 'لا توجد بيانات رواتب',
    payrollConfirm: 'تأكيد صرف الرواتب؟ سيتم تسجيل المرتبات في الخزنة.',
    payrollSuccess: 'تم صرف الرواتب وتسجيلها في الخزنة',
    generatePayroll: 'إنشاء كشف الرواتب',
    exportPayroll: 'تصدير كشف Excel',

    // Notifications
    notifications: 'الإشعارات',
    noNotifications: 'لا توجد إشعارات',
    markAllRead: 'تحديد الكل كمقروء',
    lowStockAlert: 'مخزون منخفض',
    dealClosingAlert: 'صفقة قاربت الإغلاق',
    overdueInvoiceAlert: 'فاتورة متأخرة السداد',
    birthdayAlert: 'عيد ميلاد موظف',
    payrollAlert: 'موعد استحقاق الرواتب',
    myProfile: 'الملف الشخصي للموظف',
    personalInfo: 'المعلومات الشخصية',
    salaryHistory: 'مسيرات الرواتب السابقة',
    advancesDeductions: 'السلف والخصومات المالية',
    recentAttendance: 'سجل الحضور الأخير',
    updateContact: 'تحديث بيانات التواصل',
    altPhone: 'هاتف الطوارئ',
    basicSalaryLabel: 'الراتب الأساسي',
    monthlySummary: 'ملخص الاستحقاقات (الشهر الحالي)',
    activityLogs: 'سجل عمليات النظام',
    accessDeniedTitle: 'صلاحيات محدودة',
    accessDeniedBody: 'عذراً، هذه الصفحة مخصصة للإدارة فقط.',
  },

  en: {
    // Navigation
    dashboard: 'Dashboard',
    employees: 'Staff Management',
    attendance: 'Attendance & Time',
    clients: 'Client Base',
    deals: 'Deals & Projects',
    products: 'Stock & Inventory',
    suppliers: 'Supplier List',
    transactions: 'Accounts & Treasury',
    invoices: 'Sales & Invoices',
    payroll: 'Payroll Management',
    settings: 'System Settings',

    // Auth
    signOut: 'Sign Out',
    signIn: 'Sign In',
    email: 'Email',
    password: 'Password',
    loading: 'Loading...',
    connected: 'Connected',
    register: 'Register',
    fullName: 'Full Name',
    alreadyHaveAccount: 'Already have an account?',
    noAccount: "Don't have an account? Register now",
    registrationSuccess: 'Account created successfully! You can login now.',
    newRegistration: 'New Employee Registration',
    newRegistrationBody: '{name} has registered as a new employee.',
    notifications: 'Notifications',
    markAllRead: 'Mark all as read',
    noNotifications: 'No new notifications',
    lowStockAlert: 'Low Stock Alert',
    dealClosingAlert: 'Deal Closing Alert',
    overdueInvoiceAlert: 'Overdue Invoice Alert',
    payrollAlert: 'Payroll Due Date',
    myProfile: 'Employee Profile',
    personalInfo: 'Personal Information',
    salaryHistory: 'Previous Payroll History',
    advancesDeductions: 'Advances & Deductions',
    recentAttendance: 'Recent Attendance Logs',
    updateContact: 'Update Contact Details',
    altPhone: 'Emergency Contact',
    basicSalaryLabel: 'Basic Salary',
    monthlySummary: 'Monthly Entitlements Summary',
    activityLogs: 'System Activity Logs',
    accessDeniedTitle: 'Restricted Access',
    accessDeniedBody: 'Sorry, this page is restricted to administrative staff.',
    present: 'Present',
    absent: 'Absent',
    leave: 'Leave',
    holiday: 'Holiday',
    vegetables: 'Vegetables',
    fruits: 'Fruits',
    legumes: 'Legumes',
    kg: 'Kilogram (kg)',
    ton: 'Metric Ton',
    carton: 'Carton',
    sack: 'Sack / Bag',
    piece: 'Piece / Unit',
    contact: 'Initial Contact',
    negotiation: 'Negotiation',
    contracted: 'Contract Signed',
    facebook: 'Facebook',
    instagram: 'Instagram',
    google: 'Google',
    referral: 'Referral',
    direct: 'Direct',
    other: 'Other',
    retail: 'Retail',
    wholesale: 'Wholesale',

    // Settings Page
    settingsTitle: 'System Settings',
    settingsSubtitle: 'Manage your company data and system preferences',
    companyInfo: 'Company Information',
    companyName: 'Company Name',
    companyAddress: 'Address',
    companyPhone: 'Phone Number',
    companyEmail: 'Email Address',
    taxNumber: 'Tax Number',
    currency: 'Currency',
    currencySymbol: 'Currency Symbol',
    companyLogo: 'Company Logo',
    uploadLogo: 'Upload New Logo',
    logoHint: 'PNG or JPG, max size 2MB',
    logoPreview: 'Logo Preview',
    noLogo: 'No Logo',

    // Invoice Settings
    invoiceSettings: 'Invoice Settings',
    invoiceNotes: 'Invoice Notes',
    invoiceFooter: 'Invoice Footer',
    invoiceColor: 'Invoice Color',
    invoicePrefix: 'Invoice Number Prefix',
    invoiceTaxRate: 'Tax Rate %',
    invoiceShowLogo: 'Show Logo on Invoice',
    invoiceShowTax: 'Show Tax',
    invoiceNotesPlaceholder: 'Thank you for your business...',
    invoiceFooterPlaceholder: 'Bank: ××× | Account: ×××',

    // Payroll Settings
    payrollSettings: 'Payroll Settings',
    payrollDay: 'Payroll Day',
    workingHours: 'Daily Working Hours',
    latePenaltyPerHour: 'Late Penalty (per hour)',

    // Notification Settings
    notificationSettings: 'Notification Settings',
    notifyLowStock: 'Low Stock Alert',
    notifyLowStockDays: 'Minimum Stock Level',
    notifyDealsClosing: 'Deals Closing Soon Alert',
    notifyDealsClosingDays: 'Days Before',
    notifyOverdueInvoices: 'Overdue Invoices Alert',
    notifyBirthdays: 'Employee Birthdays Alert',
    notifyPayroll: 'Payroll Due Alert',

    // User Management
    userManagement: 'User Management',
    userManagementSubtitle: 'Control user roles and permissions',
    changeRole: 'Change Role',
    roleUpdated: 'Role Updated',

    // Language Settings
    languageSettings: 'Language Settings',
    languageLabel: 'Interface Language',
    arabic: 'العربية',
    english: 'English',
    direction: 'Text Direction',
    rtl: 'Right to Left (RTL)',
    ltr: 'Left to Right (LTR)',

    // Actions
    save: 'Save Changes',
    saving: 'Saving...',
    saved: 'Saved Successfully',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    export: 'Export Excel',
    exportPDF: 'Export PDF',
    print: 'Print',
    preview: 'Preview',
    view: 'View',

    // Status
    active: 'Active',
    inactive: 'Inactive',
    pending: 'Pending',
    draft: 'Draft',
    sent: 'Sent',
    paid: 'Paid',
    cancelled: 'Cancelled',
    overdue: 'Overdue',

    // Roles
    admin: 'Admin',
    employee: 'Employee',
    manager: 'General Manager',
    accountant: 'Accountant',
    sales: 'Sales Representative',
    hr: 'HR',
    labor: 'Labor',
    station: 'Station',
    allStations: 'All Stations',
    allRoles: 'All Roles',
    selectStation: 'Select Station',

    // Errors
    errorSaving: 'An error occurred while saving',
    errorUploading: 'An error occurred while uploading',
    errorLoading: 'An error occurred while loading',
    fileTooLarge: 'File is too large (max 2MB)',
    invalidFileType: 'Unsupported file type',
    accessDenied: 'You do not have permission to access this page',

    // Dashboard
    welcomeBack: 'Welcome Back',
    totalEmployees: 'Total Employees',
    totalClients: 'Total Clients',
    totalDeals: 'Total Deals',
    totalRevenue: 'Total Revenue',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    presentToday: 'Present Today',
    activeDeals: 'Active Deals',
    lowStockItems: 'Low Stock Items',
    monthRevenue: 'Month Revenue',
    monthExpense: 'Month Expenses',
    revenueExpenseChart: 'Revenue & Expenses',
    last6Months: 'Last 6 Months',
    latestTransactions: 'Latest Transactions',
    noTransactions: 'No transactions yet',
    revenue: 'Revenue',
    expense: 'Expense',
    salary: 'Salary',
    advance: 'Advance',
    deduction: 'Deduction',
    waste: 'Waste',
    purchase_payment: 'Supplier Payment',
    client_payment: 'Client Payment',
    maintenance: 'Maintenance',
    aiInsights: 'AI Insights',
    stationComparison: 'Station Comparison (Finance)',
    expenseBreakdown: 'Expense Breakdown (This Month)',
    all: 'All',

    // Common
    name: 'Name',
    phone: 'Phone',
    address: 'Address',
    date: 'Date',
    amount: 'Amount',
    total: 'Total',
    status: 'Status',
    actions: 'Actions',
    notes: 'Notes',
    user: 'User',
    role: 'Role',
    noData: 'No data available',
    confirm: 'Confirm',
    close: 'Close',
    yes: 'Yes',
    no: 'No',
    from: 'From',
    to: 'To',
    month: 'Month',
    year: 'Year',
    subtotal: 'Subtotal',
    tax: 'Tax',
    discount: 'Discount',
    net: 'Net',
    quantity: 'Quantity',
    unitPrice: 'Unit Price',
    description: 'Description',
    item: 'Item',
    addItem: 'Add Item',
    removeItem: 'Remove Item',
    nameRequired: 'Name is required',
    invalidAmount: 'Enter a valid amount',
    transaction: 'Transaction',
    cash: 'Cash',
    transfer: 'Bank Transfer',
    check: 'Check',
    nameRequired: 'Name is required',
    updateSuccess: 'Updated successfully',
    addSuccess: 'Added successfully',
    deleteConfirm: 'Are you sure you want to delete?',
    deleteSuccess: 'Deleted successfully',
    noActiveEmployees: 'No active employees',

    // Invoices
    newInvoice: 'New Invoice',
    invoiceNumber: 'Invoice Number',
    invoiceDate: 'Issue Date',
    dueDate: 'Due Date',
    client: 'Client',
    deal: 'Deal',
    invoiceItems: 'Invoice Items',
    invoiceTotal: 'Invoice Total',
    markAsPaid: 'Mark as Paid',
    markAsSent: 'Mark as Sent',
    confirmDelete: 'Are you sure you want to delete?',
    generatePDF: 'Generate PDF',
    invoicePreview: 'Invoice Preview',
    noInvoices: 'No invoices yet',

    // Payroll
    payrollTitle: 'Payroll',
    payrollSubtitle: 'Calculate and process employee salaries',
    basicSalary: 'Basic Salary',
    attendanceDays: 'Attendance Days',
    absenceDays: 'Absence Days',
    overtimeHours: 'Overtime Hours',
    overtimeAmount: 'Overtime Amount',
    bonuses: 'Bonuses',
    deductions: 'Deductions',
    advances: 'Month Advances',
    netSalary: 'Net Salary',
    calculatePayroll: 'Calculate Payroll',
    payAll: 'Pay All',
    paySingle: 'Pay',
    payrollPaid: 'Paid',
    payrollDraft: 'Draft',
    noPayroll: 'No payroll data',
    payrollConfirm: 'Confirm payroll payment? Salaries will be recorded in treasury.',
    payrollSuccess: 'Payroll paid and recorded in treasury',
    generatePayroll: 'Generate Payroll',
    exportPayroll: 'Export Excel',

    // Notifications
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    markAllRead: 'Mark all as read',
    lowStockAlert: 'Low Stock',
    dealClosingAlert: 'Deal Closing Soon',
    overdueInvoiceAlert: 'Overdue Invoice',
    birthdayAlert: 'Employee Birthday',
    payrollAlert: 'Payroll Due',
  }
}

export function LangProvider({ children }) {
  const { settings, updateSettings } = useSettings()
  const [lang, setLangState] = useState('ar')

  useEffect(() => {
    if (settings?.language) {
      setLangState(settings.language)
      applyDirection(settings.language)
    }
  }, [settings?.language])

  const applyDirection = (language) => {
    const dir = language === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.dir = dir
    document.documentElement.lang = language
  }

  const setLang = useCallback(async (newLang) => {
    setLangState(newLang)
    applyDirection(newLang)
    await updateSettings({ language: newLang })
  }, [updateSettings])

  const t = useCallback((key) => {
    return translations[lang]?.[key] ?? translations['ar'][key] ?? key
  }, [lang])

  const dir = lang === 'ar' ? 'rtl' : 'ltr'
  const isRTL = lang === 'ar'

  return (
    <LangContext.Provider value={{ lang, setLang, t, dir, isRTL }}>
      {children}
    </LangContext.Provider>
  )
}
